# Generated by Django 6.0.1 on 2026-02-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlab',
            name='room_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Lab', 'Lab'), ('Seminar Hall', 'Seminar Hall')], max_length=20),
        ),
    ]
