# Generated by Django 6.0.1 on 2026-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_roomlab_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlab',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roomlab',
            name='roomNo',
            field=models.CharField(max_length=20),
        ),
    ]
